version: '3.5'
services: 
  www:
      container_name: www
      build:  
          context: .
          dockerfile: dockerfile
      
      command: python run.py
      
      volumes: 
          - .:/usr/src/www/
      ports: 
      #    - "127.0.0.1:7003:7002"
        - "5001:5002"
      environment: 
        - TZ=Europe/Moscow
      networks: 
        - net_nginx

  nginx:
      build: 
          context: ./nginx
          dockerfile: dockerfile
      ports:
          - 5000:5000
      depends_on:
          - www
      networks: 
          - net_nginx
networks: 
    net_nginx:
        driver: bridge
        # ipam:
        #     config:
        #     - subnet: 13.8.1.0/16